"""create devices and flows tables

Revision ID: 305200e81008
Revises: 
Create Date: 2026-09-09 01:59:50.046398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305200e81008'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=True)
    op.create_table('flows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_device_id'), 'flows', ['device_id'], unique=False)
    op.create_index('ix_flows_device_ts', 'flows', ['device_id', 'ts'], unique=False)
    op.create_index(op.f('ix_flows_ts'), 'flows', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flows_ts'), table_name='flows')
    op.drop_index('ix_flows_device_ts', table_name='flows')
    op.drop_index(op.f('ix_flows_device_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
